version: '3.9'

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
